# Generated by Django 3.2.9 on 2021-11-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publish_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[('pos', 'I recommend buying this product.'), ('neg', "I don't recommend buying this product.")], max_length=3),
        ),
    ]
