# Generated by Django 3.2.9 on 2021-11-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptions',
            field=models.ManyToManyField(to='products.Description'),
        ),
    ]
