# Generated by Django 3.2.9 on 2021-11-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='description',
            name='title',
            field=models.CharField(help_text='short description', max_length=128, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descriptions',
            field=models.ManyToManyField(blank=True, to='products.Description'),
        ),
    ]
