# Generated by Django 3.2.9 on 2021-11-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
                ('categories', models.ManyToManyField(blank=True, to='products.Category')),
                ('descriptions', models.ManyToManyField(blank=True, to='products.Description')),
                ('images', models.ManyToManyField(blank=True, to='products.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
