# Generated by Django 3.2.9 on 2021-11-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_feature'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.UniqueConstraint(fields=('name', 'value'), name='name-value uniqueness'),
        ),
    ]
