# Generated by Django 3.2.9 on 2021-11-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_feature_name-value uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, to='products.Feature'),
        ),
    ]
