# Generated by Django 3.2.9 on 2021-11-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_brand'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feature',
            name='name-value uniqueness',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='name',
        ),
        migrations.AddField(
            model_name='feature',
            name='parent_feature',
            field=models.ForeignKey(blank=True, default=1, help_text='for products with multiple sub features', on_delete=django.db.models.deletion.CASCADE, to='products.feature'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.UniqueConstraint(fields=('parent_feature', 'value'), name='parent-value uniqueness'),
        ),
    ]
