# Generated by Django 3.2.9 on 2021-11-26 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20211126_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='parent_feature',
            field=models.ForeignKey(blank=True, help_text='for products with multiple sub features', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.feature'),
        ),
    ]
